@startuml
class Product {
  + Product(std::string id, std::string name, double price)
  + getId() : std::string
  + getName() : std::string
  + getPrice() : double
  __
  - std::string _id
  - std::string _name
  - double _price
}
@enduml