@startuml
hide empty members

class Catalogue {
  + addProduct(Product product)
  + contains(std::string id) : bool
  __
  - _inventory : ???
}

class Product {
}

Catalogue "1" *-- "0..n" Product
@enduml