@startuml
hide empty members

class Driver {
    + Driver(std::string name)
    + Driver(std::string name, std::unique_ptr<Vehicle> vehicle_ptr)
    + assignVehicle(std::unique_ptr<Vehicle> vehicle_ptr)
    + getName() : std::string
    + getVehicle() : Vehicle*
    __
    - _name : std::string
    - _vehicle_ptr : std::unique_ptr<Vehicle>
}

class Vehicle {
}

Driver "1" o-- "0..1" Vehicle

@enduml